### ISSUE TITLE
keine Sonderzeichen in Dateinamen und Ordnernamen beim Export

### ISSUE THREAD

**Issue by AdminLebenswurzel** [lebenswurzel/solawi-bedarf#57]
Beim Export z.B. PDFs für Lieferscheine werden die Produktbezeichnungen und ähnliches als Datei und Ordnernamen genutzt. Nicht alle Sonderzeichen sind auch für Windows Systeme geeignet. Dadurch kommt es regelmässig zu Fehlermeldungen und nicht syncronisierten Dateien in der nextcloud. Es wäre schön, wenn für Ordner und Dateien nur Zeichen verwendet werden, die in jedem Betriebssystem funktionieren.

**Comment by joergrs** [comment]
Umsetzung: die unter Windows nicht unterstützen Zeichen `<>:"/\|?*` werden durch `-` ersetzt.

**Comment by R1tschY** [comment]
Fixed in 767c5be
