### ISSUE TITLE
fix for website icon

### ISSUE THREAD

**Issue by joergrs** [lebenswurzel/solawi-bedarf#69]
The website icon is currently not served properly.

Reason: the nginx.conf in the FE container doesn't forward the icon.

**Comment by joergrs** [comment]
Changing icon to https://github.com/mozilla/fxemoji/blob/gh-pages/svgs/nature/u1F331-seedling.svg to avoid amibiguous use of "aubergine".

**Comment by R1tschY** [comment]
Fixed with #72
