### ISSUE TITLE
Beschreibungen in der Verteilungsübersicht anzeigen

### ISSUE THREAD

**Issue by joergrs** [lebenswurzel/solawi-bedarf#79]
Aktuell stehen in der Verteilungsübersicht nur Daten und Kalenderwochen. Für Hilfszwecke (z.B. Mengenermittlung) legen die Verteiler aber teilweise mehrere Verteilungen an oder nennen die Verteilung "noch nicht vollständig".

Damit man schneller sieht, welche Verteilung was ist und es nicht nur an Hand des Datums erraten muss, kann einfach die Beschreibung mit eingeblendet werden.

**Comment by R1tschY** [comment]
Fixed with #80
